### ISSUE TITLE
Allow for artifact to be enabled/disabled during a run

### ISSUE THREAD

**Issue by DaltonGoesFast** [6thmoon/CurseCatcher#3]
Just a console command to turn off the optional artifact during gameplay would be nice

**Comment by 6thmoon** [comment]
The artifact implementation is unconventional to say the least, due to the server-side only support. Probably going to rewrite it completely at some point, in which case that would be fixed. For now, you can use this.
> [6thmoon-CurseCatcher-0.0.0.zip](https://github.com/6thmoon/CurseCatcher/files/12641675/6thmoon-CurseCatcher-0.0.0.zip)

**Comment by 6thmoon** [comment]
1. Go to *Settings* in **r2modman**, under *Profile* there is an button labeled `Import local mod`
2. Select this option and navigate to the `.zip` file provided
3. Make sure you have [**MidRunArtifacts** by *KingEnderBrine*](https://thunderstore.io/package/KingEnderBrine/MidRunArtifacts) installed as well
4. Once in game, enter the console command `mra_disable ArtifactofInfliction` to toggle the artifact off

**Comment by DaltonGoesFast** [comment]
Thank you!! The server side is the best feature of the mod so if you do rework it, keep it that way!! I already use MRA so thank you for this build!
